version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enova
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'

  app:
    build: .
    command: sh -c "npm run prisma:migrate && npm run prisma:seed && npm run start:dev"
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - ./:/usr/src/app

  worker:
    build: .
    command: npm run start:worker
    env_file: .env
    
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./:/usr/src/app

volumes:
  pgdata:
